[project]
name = "dicodex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.15.1",
    "selenium>=4.40.0",
]

[tool.ruff]
line-length = 79
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "W"]
extend-select = ["PTH"]
ignore = ["F401"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 72

